# Configurable item drops
# To prevent crashes or bug, the item must be writen correctly. Think of the autofill that shows up when you give yourself an item! :D
# I am open to recommendations and issues
# Made by PDevChris
drops:
  iron_ore: "minecraft:iron_block"
  diamond_ore:
    - "minecraft:diamond_helmet"
    - "minecraft:diamond_chestplate"
    - "minecraft:diamond_leggings"
    - "minecraft:diamond_boots"
    - "minecraft:diamond_sword"
  emerald_ore:
    - "minecraft:diamond_helmet:enchant:protection:1"
    - "minecraft:diamond_chestplate:enchant:protection:1"
    - "minecraft:diamond_leggings:enchant:protection:1"
    - "minecraft:diamond_boots:enchant:protection:1"
  gold_ore:
    - "minecraft:cobweb"
    - "minecraft:bow"
    - "minecraft:arrow"

# Redstone extra hearts limit
redstone:
  max_hearts: 5
